#!/bin/bash

CONFIGS=(
  "CONFIG_NET_ACT_CT=m"
  "CONFIG_NET_ACT_CTINFO=m"
  "CONFIG_ARM_SCMI_TRANSPORT_VIRTIO=y"
  "CONFIG_ARM_SCMI_TRANSPORT_VIRTIO_VERSION1_COMPLIANCE=y"
  "CONFIG_ARM_SCMI_TRANSPORT_VIRTIO_ATOMIC_ENABLE=y"
  "CONFIG_KVM=y"
  "CONFIG_NVHE_EL2_DEBUG=n"
  "CONFIG_PROTECTED_NVHE_STACKTRACE=n"
  "CONFIG_VIRTIO_MENU=y"
  "CONFIG_VIRTUALIZATION=y"
  "CONFIG_VFIO_AMBA=y"
  "CONFIG_KVM_ARM_HOST=y"
  "CONFIG_KVM_ARM_VGIC=y"
  "CONFIG_KVM_ARM_TIMER=y"
  "CONFIG_VIRTIO_NET=y"
  "CONFIG_VIRTIO_BLK=y"
  "CONFIG_VIRTIO_CONSOLE=y"
  "CONFIG_VIRTIO_MMIO=y"
  "CONFIG_VHOST_NET=y"
  "CONFIG_VHOST_VSOCK=y"
  "CONFIG_VHOST_SCSI=y"
  "CONFIG_TUN=y"
  "CONFIG_BRIDGE=y"
  "CONFIG_BRIDGE_VLAN_FILTERING=y"
  "CONFIG_IOMMU_SUPPORT=y"
  "CONFIG_ARM_SMMU=y"
  "CONFIG_ROCKCHIP_IOMMU=y"
  "CONFIG_VFIO=y"
  "CONFIG_VFIO_IOMMU_TYPE1=y"
  "CONFIG_VFIO_PLATFORM=y"
  "CONFIG_USB_UAS=n"
)

source .current_config.mk
KCFG=kernel/arch/arm64/configs/$(awk '{print $1}' <<< "$TARGET_KERNEL_CONFIG")

for CFG in "${CONFIGS[@]}"; do
  KEY=${CFG%%=*}
  if grep -q "^#\?${KEY}=" "${KCFG}"; then
    sed -i "s@^#\?${KEY}=.*@${CFG}@g" "${KCFG}"
  else
    echo "$CFG" >> "${KCFG}"
  fi
done
